In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3])
arr2 = np.array([[2,3,4],[9,8,7]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndarray

AttributeError: 'numpy.ndarray' object has no attribute 'ndarray'

In [5]:
arr.ndim

1

In [6]:
arr.shape

(3,)

In [7]:
arr.size

3

In [8]:
arr.dtype

dtype('int32')

In [9]:
c=np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
np.zeroes((3,4))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.arrange?

Object `np.arrange` not found.


In [15]:
np.arange?

In [16]:
f = np.arange(0,30,5)
print(f)

[ 0  5 10 15 20 25]


In [17]:
g = np.linspace(0,5,10)
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [18]:
print(arr1)

NameError: name 'arr1' is not defined

In [19]:
print(arr2)

NameError: name 'arr2' is not defined

In [20]:
print(arr2)

NameError: name 'arr2' is not defined

In [21]:
a1 = np.array([[1,2,3,4],
              [9,8,7,6],
              [-1,0,5,2,9]])
print(a1,"\n")
newa1 = a1.reshape((2,6))
print(newa1)

[list([1, 2, 3, 4]) list([9, 8, 7, 6]) list([-1, 0, 5, 2, 9])] 



ValueError: cannot reshape array of size 3 into shape (2,6)

In [22]:
a1 = np.array([[1,2,3,4],
              [9,8,7,6],
              [-1,0.5,2,9]])
print(a1,"\n")
newa1 = a1.reshape((2,6))
print(newa1)

[[ 1.   2.   3.   4. ]
 [ 9.   8.   7.   6. ]
 [-1.   0.5  2.   9. ]] 

[[ 1.   2.   3.   4.   9.   8. ]
 [ 7.   6.  -1.   0.5  2.   9. ]]


In [23]:
a1.T

array([[ 1. ,  9. , -1. ],
       [ 2. ,  8. ,  0.5],
       [ 3. ,  7. ,  2. ],
       [ 4. ,  6. ,  9. ]])

In [24]:
a1.max

<function ndarray.max>

In [25]:
a1.max()

9.0

In [26]:
a1.max(axis=1)

array([4., 9., 9.])

In [27]:
a1.max(axis=0)

array([9., 8., 7., 9.])